language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: codehutlabs
  password:
    secure: "SRqoEtNLbmT9/PCl2r/Lvq3IuvODlnUNIRAnmT07WBQR3qA7DGoRry6shEDQuot0B830h0k2LKLFTpC6xdoUdiQ9lmD9NWPgGAM6pZaHqWUlOLRetSMqsEVUWR9B1H4iuftbfzNQ8/m0a88d4/Ce5mT+tg1/d4nXVLuLBTvb5ZWo/zcNdOvwY7s2TSryTxfcTTUk1bE/F0zRgSCAwD04kh1FcoNbbbokLrKNszPBShnfsYEjXRIwMjVCVGcuB2GfwB/NJwK90PjJy3V48SWwavteO20Tod79cz0wI0BwbYTBvX6saNp9WW32BpJc0JACcUCF3FA0FJB7wBYS06FWFYgS+otr1gAQhkjJ/4F5ptW3fR78xRCDSsiH34ij8orw3jRCvW2SOi6+Xa/hGMgsP8SoG45djNiSDjRPjl2T+Wl4Tx5VHPMER3vzY091qbh/7wzXeSh4CHkTmWZo2myh5an12igQjQBsCkY83wKIR43f7CkMDKz5dl7b1v4KIILXtSqT8203hVyJxWVB5yyQRVZRFMgdxGkkdEdkPC5YQeLdQSuLPQ1s+fs0qnU8EagC8LZ3K9xGDFYWOFxpiHQO7F+4NA9LKnoqwk7T4RzCRyTJl6FJOL0SL6OBpNU8AcEOBgItiGqWzUhFQC85r+VArPtoBlKzoVPIj+O+ncf3ivw="
  on:
    tags: true
    repo: codehutlabs/slugifile
    python: 3.6
