language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: codehutlabs
  password:
    secure: DVNzVGr5TG216DmrLvmsCS6xSwHnmNPm6jQ48c1LTJqgZwP1P2tc6xF1PjRGADihj4F1pZRVAbJSGQLsFnccNPvs0zRtjYn1VDg5Z/QnDApBaMkUMqC1UnOgpJTba+BUokyx+53mFrsT2yQx2P5qBBKXzU0PlXYTPycLl5CAwDbqK7CQedY28nxIf3BRUBoRSl2Uz9fVCs1+WDt97X/PHPMyzdFnfEE1fOAIkfL1926g5MfAuHd25xSlydfk6JfOQYFsGlHC4C9WGMS3WZDU7x1oU8AoE8mz99fRs/fVy+9+QILZYN65DNCwkWTWQV0rYmiqQBn1IlamcEFwR6aaWeXiSsEaWZpyKxWvtCmDa7OEpFay5yDfLXY70D/s4nxxy7j0xJYlrH1RAfEcRgws59gDMwTkEdiSKtEeieO1OB0KgSnQybm/pJnVC6r6q/OhpzhqEOLgAjodL50C+De9BEoTC+yz5+wMWd0NqWsZ8vUwqKAhex5PcH1BRs6uXrkQ1p5h6aJY/c/MRI0e75Xn/RdPIS+3FWn5EgLscMLh2g9+jHHE3+HTve7UbJ9ZrrLLFmQbIvuCetCrT2eT9ZM6INdOHDYZ6ueBSIXA6jKPq3cw8q+KXRYpYj/4E9x8yP3BYLT8w03XR0Suq4fAX/QGrSpHCX/Sr0PC68S3yp4V+8c=
  on:
    tags: true
    repo: codehutlabs/slugifile
    python: 3.6
