language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: codehutlabs
  password:
    secure: "NJTRm5BEiVeE9gMVfpNGFXyWDfiPfnlfjB/Si6jTd5JJI7GhiqEhrKXM4iYUSOk/GlwGd2F1pvIIeLp8qvlyLcsWLy/DMO7aJNwraJNHvRAd7yaL9e9P9RrYfBuryuUDqPMUIgnaRS4ScvJ4/u9HojTlLJXky2qRbQjAYYv1fo1e/nS+kcQ3Dmo1rxiJfFpuiPwI2yYSczVRu0dihz9HyHaw6+RJurgTkTnl9aO1lBnEkx7jSxWCBvdux4wX/iMtym4GmxlLtjRoRU88jFkj+sz1fJIJm6f9Orid3lnCO8oWCmg/keujC+qxKBysmXiJsDxSkkPPZ4VlEVc/07iCZtn3YoBlWbI2dM/J/MyiVNFFeOApL7FhQ7vGgCMVel5jUP+eFLiyUUxJiVYIjUDvW/YvzxNx8H8tI+Av8VbdjTPq99sRmDmI41cwzTJAwGyw3npIR5OSXNg1VfHtF3HQfrx6skPtFDZpPtQS6yilv6ahCcRgHKErRAD4lw+5Kddf0Ubps0CDfFoHGYVejAovv9VTAH9/LbfFXwONmqmzlpxM5UYntt1R//ckaHkf9CDSasc6D7IEH3eFYj/tHOCtyohFoJmjbSIii+kkoh1AgKTaVmpprrXZxYrfrUi+fDKZBLqCqZGREsR1ioGuTHDog0pWIQapx4540WCgb1LWbLg="
  on:
    tags: true
    repo: codehutlabs/slugifile
    python: 3.6
